name: ufs
channels:
        - conda-forge
dependencies:
        - python=3.7
        - f90nml
        - jinja2
        - pyyaml
        - scipy
        - matplotlib
        - scipy
        - pint
        - netcdf4
        - jupyter
        - jupyterlab
        - xarray
        - pandas
        - pyproj
        - cartopy
        - geopandas
        - cfgrib
        - pynio
        - tqdm
        - wrf-python
        - sparse
        - dask
        - arm_pyart
        - ipykernel
        - metpy

