name: ufs
channels:
        - conda-forge
dependencies:
        - python=3.7
        - f90nml=1.1.2
        - jinja2=2.11
        - pyyaml=5.1.2
        - scipy
        - matplotlib
        - scipy
        - pint
        - netcdf4
        - jupyter
        - jupyterlab
        - xarray
        - pandas
        - pyproj
        - cartopy
        - geopandas
        - cfgrib
        - pynio
        - tqdm
        - wrf-python
        - sparse
        - dask
        - arm_pyart
        - black
        - isort
        - pip
        - pip:
                git+https://github.com/jthielen/MetPy.git@edge
